### PR TITLE
Two potential issues that can be fixed

### PR DESCRIPTION
**Pull request by SnowNooDLe**
1. ParserMike for checking the second value as if user do U D, penup or pendown, will be crashed by out of index
2. convert_direction may not work ?

### CODE REVIEW

**Comment by forestraindrip** [comment]
The main reason of direction issue is all parsers set 
north 0
east 90
south 180
west 270
clockwise rotation

However, if we follow the default the coordinate system
east 0
north 90
west 180
south 270
counter clockwise rotation
Then a lot of issue can be solved naturally

**Comment by forestraindrip** [comment]
My bad.
I use script to test the turtle
Missed the E and W
Fixing now

**Comment by forestraindrip** [comment]
Turtle use different coordinate system
The angle system of these three drawer are different as well.
I would say better not to make any big change by now.

**Comment by SnowNooDLe** [comment]
Also, double check with another changes I made, was playing with go_along & go_down, it seems working different between turtle and PyGame & TKInter

**Comment by forestraindrip** [comment]
That why I wrote the function in turtle to solve the inconsistency

**Pull request closed without merging**
